### ISSUE TITLE
Start fails with "no unix-java in java.library.path" 

### ISSUE THREAD

**Issue by jeanparpaillon** [gibello/erocci-dbus-java#1]
Followed instructions in README:
- run with Debian / openjdk 7
- dbus-java-install-script.sh
- mvn exec:java -Dexec.mainClass="org.ow2.erocci.backend.BackendDBusService"

I got the following error:

mvn exec:java -Dexec.mainClass="org.ow2.erocci.backend.BackendDBusService" 
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.occiware.erocci.java:erocci-dbus-java:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 90, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building erocci-dbus-java 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.windwards.3rdparty:dbus:jar:2.8 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for net.windwards.3rdparty:dbus-bin:jar:2.8 is missing, no dependency information available
[WARNING] The POM for net.windwards.3rdparty:matthew-hexdump:jar:0.2 is missing, no dependency information available
[WARNING] The POM for net.windwards.3rdparty:matthew-debug:jar:1.1 is missing, no dependency information available
[WARNING] The POM for net.windwards.3rdparty:matthew-unix:jar:0.5 is missing, no dependency information available
[INFO] 
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ erocci-dbus-java ---
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: no unix-java in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at cx.ath.matthew.unix.UnixSocket.<clinit>(UnixSocket.java:33)
	at org.freedesktop.dbus.Transport.connect(Transport.java:772)
	at org.freedesktop.dbus.Transport.<init>(Transport.java:737)
	at org.freedesktop.dbus.DBusConnection.<init>(DBusConnection.java:299)
	at org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:282)
	at org.ow2.erocci.backend.BackendDBusService.start(BackendDBusService.java:29)
	at org.ow2.erocci.backend.BackendDBusService.main(BackendDBusService.java:43)
	... 6 more

**Comment by jeanparpaillon** [comment]
I know that the error comes from unix-java.so not being installed in the right place.
Can't maven install it "in the right place" ? For those not familiar with Java, it is not straight forward at all.

**Comment by jeanparpaillon** [comment]
Started with openjdk 7, after copying libunix-java.so into <jdk>/lib/amd64:

$ java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

Run: 
$ DBUS_SESSION_BUS_ADDRESS=$(printenv DBUS_SESSION_BUS_ADDRESS | sed -e 's/kernel:.*;//') mvn exec:java -Dexec.mainClass="org.ow2.erocci.backend.BackendDBusService"
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.occiware.erocci.java:erocci-dbus-java:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 90, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building erocci-dbus-java 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.windwards.3rdparty:dbus:jar:2.8 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for net.windwards.3rdparty:dbus-bin:jar:2.8 is missing, no dependency information available
[WARNING] The POM for net.windwards.3rdparty:matthew-hexdump:jar:0.2 is missing, no dependency information available
[WARNING] The POM for net.windwards.3rdparty:matthew-debug:jar:1.1 is missing, no dependency information available
[WARNING] The POM for net.windwards.3rdparty:matthew-unix:jar:0.5 is missing, no dependency information available
[INFO] 
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ erocci-dbus-java ---
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: no unix-java in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at cx.ath.matthew.unix.UnixSocket.<clinit>(UnixSocket.java:33)
	at org.freedesktop.dbus.Transport.connect(Transport.java:772)
	at org.freedesktop.dbus.Transport.<init>(Transport.java:737)
	at org.freedesktop.dbus.DBusConnection.<init>(DBusConnection.java:299)
	at org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:282)
	at org.ow2.erocci.backend.BackendDBusService.start(BackendDBusService.java:29)
	at org.ow2.erocci.backend.BackendDBusService.main(BackendDBusService.java:43)
	... 6 more

**Comment by jeanparpaillon** [comment]
@mdutoo @gibello : 
1. the workaround does not work on my machine :(
2. Anyway, it would be nice these workaround be coded into a startup script

**Comment by gibello** [comment]
Le 15/01/2016 14:44, Jean Parpaillon a écrit :
>
> @mdutoo <https://github.com/mdutoo> @gibello 
> <https://github.com/gibello> :
> 1. the workaround does not work on my machine :(
> 2. Anyway, it would be nice these workaround be coded into a startup 
> script
>
They vary according to systems and java versions.

The dbus-java code has no commits for years, so it gets unstable with 
time - many distros and JDKs appeared after its release (and it is not 
packaged for maven... because the latest version came before maven !)

I don't believe a script will ever be able to cope with such 
instability. At least, we are far from being able to provide a reliable one.

By now, we have to document errors and workarounds. We'll see later if 
we can provide any exhaustive solution...

**Comment by jeanparpaillon** [comment]
Fixed in eac19bd0f947eae6ff4259585c22e7480690f594
