### ISSUE TITLE
dbus-java fails with kernel based dbus

### ISSUE THREAD

**Issue by jeanparpaillon** [gibello/erocci-dbus-java#3]
Recent distros have integrated kernel based dbus (by default in Fedora, as a separate package in Debian). dbus-java fails starting with it.
This could be easily solved as kernel dbus has a compatibility mode:
session dbus address is specified with environment variable DBUS_SESSION_BUS_ADDRESS environment variable

In the case of daemon based dbus, DBUS_SESSION_BUS_ADDRESS=unix:path=/path/to/socket
In the case of kernel based dbus, DBUS_SESSION_BUS_ADDRESS=kernel:path=/sys/fs/kdbus/1000-user/bus;unix:path=/run/user/1000/bus

So, dbus-java could just ignore the first address (kernel:path=...) and fallback to the second one (unix:path=...).

**Comment by jeanparpaillon** [comment]
Waiting for a fix, the workaround is to launch backend with modified environment variable:

DBUS_SESSION_BUS_ADDRESS=$(printenv DBUS_SESSION_BUS_ADDRESS | sed -e 's/kernel:.*;//')

**Comment by gibello** [comment]
On Ubuntu, we have:
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/path/to/socket
And it works...
What is exactly the error message when it fails ? I will add that tip to a "troubleshooting" doc.

**Comment by jeanparpaillon** [comment]
On Debian with kdbus-dkms:
$ printenv DBUS_SESSION_BUS_ADDRESS
kernel:path=/sys/fs/kdbus/1000-user/bus;unix:path=/run/user/1000/bus

And the error:
org.freedesktop.dbus.exceptions.DBusException: Failed to connect to bus unknown address type kernel
	at org.freedesktop.dbus.DBusConnection.<init>(DBusConnection.java:304)
	at org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:282)
	at org.ow2.erocci.backend.BackendDBusService.start(BackendDBusService.java:29)
	at org.ow2.erocci.backend.BackendDBusService.main(BackendDBusService.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jeanparpaillon** [comment]
Commit eac19bd0f947eae6ff4259585c22e7480690f594 provides a workaround.
Should we close ?

**Comment by gibello** [comment]
Done.
